piece_types = [
    'King',
    'Rook',
    'Bishop',
    'Gold',
    'Silver',
    'Knight',
    'Lance',
    'Pawn',
    'Dragon',
    'Horse',
    'PromotedSilver',
    'PromotedKnight',
    'PromotedLance',
    'PromotedPawn',
]

promoted_piece_types = [
    'King',
    'Dragon',
    'Horse',
    'Gold',
    'PromotedSilver',
    'PromotedKnight',
    'PromotedLance',
    'PromotedPawn',
    'Dragon',
    'Horse',
    'PromotedSilver',
    'PromotedKnight',
    'PromotedLance',
    'PromotedPawn',
]

demoted_piece_types = [
    'King',
    'Rook',
    'Bishop',
    'Gold',
    'Silver',
    'Knight',
    'Lance',
    'Pawn',
    'Rook',
    'Bishop',
    'Silver',
    'Knight',
    'Lance',
    'Pawn',
]
